[jabley] remove deployment::creds
Removing for now so that boxen will cleanly install.

encfs wasn’t installing on my new machine for some reason.

```
Error: Execution of 'brew boxen-install encfs' returned 1: ==> Installing encfs dependency: git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.3.5.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/git-2.3.5.tar.xz
==> make prefix=/opt/boxen/homebrew/Cellar/git/2.3.5 sysconfdir=/opt/boxen/homebrew/etc CC=clang CFLAGS= LDFLAGS= install
==> make CC=clang CFLAGS= LDFLAGS=
==> make clean
==> make CC=clang CFLAGS= LDFLAGS=
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.3.5.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/git--man-2.3.5.tar.xz
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.3.5.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/git--html-2.3.5.tar.xz
==> Caveats
The OS X keychain credential helper has been installed to:
  /opt/boxen/homebrew/bin/git-credential-osxkeychain

The "contrib" directory has been installed to:
  /opt/boxen/homebrew/share/git-core/contrib

Bash completion has been installed to:
  /opt/boxen/homebrew/etc/bash_completion.d

zsh completion has been installed to:
  /opt/boxen/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/boxen/homebrew/Cellar/git/2.3.5: 1363 files, 31M, built in 25 seconds
==> Installing encfs
==> Downloading https://github.com/vgough/encfs/archive/v1.8.1.tar.gz
Already downloaded: /opt/boxen/cache/homebrew/encfs-1.8.1.tar.gz
==> make -f Makefile.dist
==> ./configure --prefix=/opt/boxen/homebrew/Cellar/encfs/1.8.1 --with-boost=/opt/boxen/homebrew
checking for fuse_new in -losxfuse... yes
checking For supported FUSE API version... no
configure: error: in `/private/tmp/encfs20150420-38497-odqd9x/encfs-1.8.1':
configure: error: Encfs 1.3 requires FUSE 2.5 or newer.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
encfs - no  target `encfs-man.html' - (with cask) yosemite  (https://github.com/Homebrew/homebrew/issues/38359)
Error: /Stage[main]/Projects::Deployment::Creds/Package[encfs]/ensure: change from absent to present failed: Execution of 'brew boxen-install encfs' returned 1: ==> Installing encfs dependency: git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.3.5.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/git-2.3.5.tar.xz
==> make prefix=/opt/boxen/homebrew/Cellar/git/2.3.5 sysconfdir=/opt/boxen/homebrew/etc CC=clang CFLAGS= LDFLAGS= install
==> make CC=clang CFLAGS= LDFLAGS=
==> make clean
==> make CC=clang CFLAGS= LDFLAGS=
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.3.5.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/git--man-2.3.5.tar.xz
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.3.5.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/git--html-2.3.5.tar.xz
==> Caveats
The OS X keychain credential helper has been installed to:
  /opt/boxen/homebrew/bin/git-credential-osxkeychain

The "contrib" directory has been installed to:
  /opt/boxen/homebrew/share/git-core/contrib

Bash completion has been installed to:
  /opt/boxen/homebrew/etc/bash_completion.d

zsh completion has been installed to:
  /opt/boxen/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/boxen/homebrew/Cellar/git/2.3.5: 1363 files, 31M, built in 25 seconds
==> Installing encfs
==> Downloading https://github.com/vgough/encfs/archive/v1.8.1.tar.gz
Already downloaded: /opt/boxen/cache/homebrew/encfs-1.8.1.tar.gz
==> make -f Makefile.dist
==> ./configure --prefix=/opt/boxen/homebrew/Cellar/encfs/1.8.1 --with-boost=/opt/boxen/homebrew
checking for fuse_new in -losxfuse... yes
checking For supported FUSE API version... no
configure: error: in `/private/tmp/encfs20150420-38497-odqd9x/encfs-1.8.1':
configure: error: Encfs 1.3 requires FUSE 2.5 or newer.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
encfs - no  target `encfs-man.html' - (with cask) yosemite  (https://github.com/Homebrew/homebrew/issues/38359)
```