[jabley] track boxen changes
Remove Ruby 1.8.7 entirely. Fixes:

```
Notice: Compiled catalog for gds0377.local in environment production in 6.26 seconds
Error: Could not find dependency Ruby::Version[1.8.7-p375] for File[/opt/rubies/1.8.7] at /opt/boxen/repo/shared/ruby/manifests/alias.pp:33
```

Remove ssh-copy-id since that is now provided by the infrastructure team
profile as of 19326dcb31.

Remove pp-deploy-lag-radiator repo since that is now provided by the
performance platform team profile as of aca115f2af.