Upgrade to latest modules and git to 1.9.1-boxen1
This updates some stuff to the latest modules. It enables more recent
builds of ruby and more notably upgrades git from 1.8.4 to 1.9.1

I noticed a snag with the git upgrade, that if you have an outdated
homebrew version (as I did), because of a change in the git brew, you
need to update homebrew first with `brew update` otherwise you will get
an error like:

```
Error: /Stage[main]/Git/Package[boxen/brews/git]/ensure: change from
1.8.4-boxen2 to 1.9.1-boxen1 failed: Could not update: Execution of
'brew boxen-upgrade boxen/brews/git' returned 1: Warning: Building
source; cellar of git's bottle is /usr/local/Cellar
==> Upgrading 1 outdated package, with result:
git 1.9.1-boxen1
==> Upgrading git
==> Downloading
https://www.kernel.org/pub/software/scm/git/git-1.9.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/git-1.9.1-boxen1.tar.gz
Error: undefined method `[]' for Formula:Class'`
```